### PR TITLE
fix(OnyxPageLayout): stabilize layout structure

### LINKED ISSUE #484: Define stabilize slot switching in the alpha-test-app layout demo
Origin: https://github.com/SchwarzIT/onyx/pull/470/files#r1512515713

In `apps/alpha-test-app/src/views/LayoutDemoView.vue`, find a way to stabilize the breaking layout on frequent config switching without using key:
Image

### Steps to reproduce the issue:
1. remove the `:key` setting displayed above.
2. start the alpha-test-app
3. open http://localhost:5173/layout-demo
4. select "Sidebar Options" > "Overlay Sidebar"
5. close the overlay sidebar via close button
6. select "Footer Options" > "Full Footer"
7. select "Sidebar Options" > "Fixed Sidebar"

Now the whole layout is broken. 
Investigation showed that the computed `pageModifier` in `packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue` did not fire when the sidebar slot was removed and re-added so the selected class is still `"onyx-page--main-footer""` even though there is a side bar.

### Implementation Hints

Idea: instead of hiding the slot parents with v-if, just let them be empty? maybe the grid itself can handle it already (the column/row use max-content anyways).

### Review

- __playwright screenshot__
- [ ] approved by designer @jannick-ux
- [ ] approved by dev __todo__

### PR DESCRIPTION
**Pull request by BoppLi**
Closes #484

Stabilizes OnyxPageLayout by using v-show instead of v-if.

### CODE REVIEW

File: packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue [hunk 1]
```diff
@@ -17,31 +17,27 @@ const slots = defineSlots<{
...
     </aside>
     <main class="onyx-page__main">
       <slot></slot>
     </main>
-    <footer v-if="slots.footer" class="onyx-page__footer">
+    <footer v-show="slots.footer" class="onyx-page__footer">
       <slot name="footer"></slot>
     </footer>
-    <div v-if="slots.toasts" class="onyx-page__toasts">
+    <div v-show="slots.toasts" class="onyx-page__toasts">
```
Comment (larsrickert) [inline packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue:40]: Toast will be displayed fixed using the popover API, right so I think this slot is obsolete :)

File: packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue [hunk 2]
```diff
@@ -17,31 +17,27 @@ const slots = defineSlots<{
...
+    mode = "onyx-page--footer-full";
   }
   return mode;
 });
 </script>
 
 <template>
   <div class="onyx-page" :class="pageModifier">
-    <aside v-if="slots.sidebar && !props.hideSidebar" class="onyx-page__sidebar">
+    <aside v-show="slots.sidebar && !props.hideSidebar" class="onyx-page__sidebar">
```
Comment (larsrickert) [inline packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue:31]: I would prefer to not render the sidebar/footer if its not set, otherwise it might be weird if it shows in the dev tools although it is not needed.

Can you extend why the slot switching is not stable in the first place? Slots and properties are reactive so I assume the issue is related to the application, not onyx itself

**Review by larsrickert — CHANGES_REQUESTED** [review]

File: packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue (hunk 1 above)
Comment (BoppLi) [reply packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue:40]: I thought about that but as soon as we get the bottom bar we might need to rethink the approach?

File: packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue (hunk 2 above)
Comment (BoppLi) [reply packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.vue:31]: The computed in line 18 `pageModifier` did not get updated with the described steps to reproduce.

But actually, with the change that it now only depends on 1 prop, it's stable already - we can keep v-if 🎉

**Review by larsrickert — APPROVED** [review]
