### PR TITLE
docs: fix conflicting styles with VitePress

### LINKED ISSUE #863: Fix VitePress styles
Due to #338, VitePress will override many styles for onyx components, e.g. like on our home page (headline and button styles are not correct)

Image

### PR DESCRIPTION
**Pull request by larsrickert**
closes #863

Prevent VitePress style for our custom onyx VitePress components so the styles are not overridden by VitePress.

### CODE REVIEW

File: apps/docs/src/.vitepress/components/DesignTokenHeader.vue [hunk 1]
```diff
@@ -17,19 +18,19 @@ const emit = defineEmits<{
 </script>
 
 <template>
-  <div class="header">
+  <div class="header vp-raw">
```
Comment (BoppLi) [inline apps/docs/src/.vitepress/components/DesignTokenHeader.vue:21]: image

should we center-align the headline with the button text or baseline it?

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue [hunk 2]
```diff
@@ -55,7 +55,7 @@ const shouldShowAllButton = computed(() => {
   <section class="components">
```
Comment (BoppLi) [inline apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: I noticed something weird. the "Components" headline looks different in storybook vs the vitepress docs on your branch.

image

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue [hunk 3]
```diff
@@ -99,6 +99,10 @@ const shouldShowAllButton = computed(() => {
     line-height: 2.5rem;
   }
 
+  &__description {
+    margin: 0;
```
Comment (BoppLi) [inline apps/docs/src/.vitepress/components/ComponentRoadmap.vue:103]: why is it needed? on onyx.schwarz there is no margin here.
image

does not seem to have an effect in 
http://localhost:6006/?path=/docs/roadmap-componentroadmap--docs
if I turn it off either.

File: apps/docs/src/.vitepress/components/DesignTokenHeader.vue (hunk 1 above)
Comment (BoppLi) [inline apps/docs/src/.vitepress/components/DesignTokenHeader.vue:21]: the vp-raw seems to have the effect that now all the preview__areas are 2px bigger - is this intended?

image

before, the overall size of the orange colored area was e.g. 0.5rem, now only the light-orange space is 0.5rem + 1px border top and bottom

File: apps/docs/src/.vitepress/components/RoadmapCard.vue [hunk 4]
```diff
@@ -39,6 +39,9 @@ const target = computed(() => (props.href?.startsWith("http") ? "_blank" : "_sel
     border-color 0.25s,
     background-color 0.25s;
```
Comment (BoppLi) [inline apps/docs/src/.vitepress/components/RoadmapCard.vue:41]: question: is there intentionally no storybook file for this component?

**Review by BoppLi — CHANGES_REQUESTED** [review]

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue (hunk 3 above)
Comment (larsrickert) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:103]: The "vp-raw" does not work in Storybook so there it will remove the default p margin but when you look at the actual vitepress docs, the margin would be added by the browser so we need to remove it

File: apps/docs/src/.vitepress/components/DesignTokenHeader.vue (hunk 1 above)
Comment (larsrickert) [reply apps/docs/src/.vitepress/components/DesignTokenHeader.vue:21]: Nope, its fixed

File: apps/docs/src/.vitepress/components/RoadmapCard.vue (hunk 4 above)
Comment (larsrickert) [reply apps/docs/src/.vitepress/components/RoadmapCard.vue:41]: Propably not, I added one

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue (hunk 3 above)
Comment (larsrickert) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:103]: It has an effect for me 🤔

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue (hunk 2 above)
Comment (larsrickert) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: Looks the same for me, did you run `pnpm install`?

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue (hunk 3 above)
Comment (BoppLi) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:103]: weird.. ok, can't hurt to have it ^^ ¯\\_(ツ)\_/¯

**Review by BoppLi — APPROVED** [review]

File: apps/docs/src/.vitepress/components/ComponentRoadmap.vue (hunk 2 above)
Comment (BoppLi) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: nope, still different.
image

Comment (BoppLi) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: computed styles of the headline (h2) from vitepress
```
box-sizing border-box
color rgb(62, 89, 110)
display block
font-family "Source Sans 3 Variable", sans-serif
font-size 40px
font-synthesis-small-caps none
font-synthesis-style auto
font-synthesis-weight none
font-weight 600
height 40px
line-height 40px
margin-block-end 0px
margin-block-start 0px
margin-bottom 0px
margin-inline-end 0px
margin-inline-start 0px
margin-left 0px
margin-right 0px
margin-top 0px
text-rendering optimizelegibility
text-size-adjust 100%
unicode-bidi isolate
width 613px
-webkit-font-smoothing antialiased
```

from storybook 
```
box-sizing border-box
color rgb(62, 89, 110)
color-scheme light
display block
font-family "Source Sans 3 Variable", sans-serif
font-size 40px
font-synthesis-small-caps none
font-synthesis-style auto
font-synthesis-weight none
font-weight 400
height 40px
line-height 40px
margin-block-end 0px
margin-block-start 0px
margin-bottom 0px
margin-inline-end 0px
margin-inline-start 0px
margin-left 0px
margin-right 0px
margin-top 0px
overflow-wrap break-word
text-rendering optimizelegibility
text-size-adjust 100%
unicode-bidi isolate
width 291px
-webkit-font-smoothing antialiased
```

Comment (BoppLi) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: font-weight differs.
left vitepress, right storybook

image

Comment (larsrickert) [reply apps/docs/src/.vitepress/components/ComponentRoadmap.vue:55]: FYI: as discussed I will close this issue. The problem is that the "vp-raw" class does only work in VitePress, not Storybook
