### PR TITLE
Fix disabled button state

### LINKED ISSUE #384: Fix disabled button state button (no hover)
**Review**
https://onyx.schwarz/development/components/OnyxButton.html
- [x] approved by designer @mj-hof
- [x] approved by dev @BoppLi

### PR DESCRIPTION
**Pull request by MajaZarkova**
closes #384 

Removed the hover effect when the button is disabled. I also adjusted the correct height of the button.

## Checklist

- [x] The added / edited code has been documented with [JSDoc](https://jsdoc.app/about-getting-started)
- [x] All changes are documented in the documentation app (folder `apps/docs`)
- [x] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added
- [x] A changeset is added with `npx changeset add` if your changes should be released as npm package (because they affect the library usage)

### CODE REVIEW

File: packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue [hunk 1]
```diff
@@ -143,6 +144,7 @@ const emit = defineEmits<{
 
   &:disabled {
     cursor: default;
+    pointer-events: none;
```
Comment (JoCa96) [inline packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue:147]: We must avoid `pointer-events: none;` as it introduces other side effects.
Instead, you could only apply the `:hover` when the button is also `:enabled`

File: packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue [hunk 2]
```diff
@@ -37,6 +37,7 @@ const emit = defineEmits<{
   --onyx-button-outline-color: var(--onyx-color-base-primary-200);
 
   display: flex;
+  height: 2.5rem;
```
Comment (JoCa96) [inline packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue:40]: You also need `box-sizing: border-box` for this to have the correct height :)

**Review by JoCa96 — CHANGES_REQUESTED** [review]

**Review by JoCa96 — APPROVED** [review]

**Review by jannick-ux — APPROVED** [review]
